version: "2"

services:
  www:
    build: www
    ports:
      - 8000:5000
    user: nobody
    environment:
      DEBUG: 1
      # List
    command: python counter.py
    #List
    volumes:
      - ./www:/src

  redis:
    image: redis
